#!/usr/bin/env php
<?php

use Ad5jp\SchemaWriter\Config;
use Ad5jp\SchemaWriter\Documentater;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require __DIR__ . '/../autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
}

Config::set($argv);

$documentater = Documentater::create();
$output = $documentater->run();

echo "\n{$output}\n";
